using System.Net;

namespace PropertyManagement.Web.Tests.Integration;

/// <summary>
/// The residence modal after it moved to its own controller.
///
/// Razor resolves both partial names and generated URLs by convention, so a wrong controller name
/// in a view compiles perfectly and fails silently at the moment somebody clicks. That is the whole
/// reason this file exists: the first test reads the links the wizard actually renders, and the
/// rest walk the routes those links point at.
/// </summary>
public class ResidenceRoutingTests(PropertyManagementApplication app)
    : IClassFixture<PropertyManagementApplication>
{
    [Fact]
    public async Task The_wizard_page_links_at_the_residences_controller()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.OwnerEmail);

        var html = await client.GetStringAsync(
            $"/RentalApplications/Edit/{app.ApplicationId}?section=ResidenceHistory");

        // Generated by Url.Action in the section partial. If the controller name were wrong or
        // missing, this would silently come back pointing at /RentalApplications instead.
        Assert.Contains("/Residences/Form", html, StringComparison.Ordinal);
        Assert.DoesNotContain("/RentalApplications/ResidenceForm", html, StringComparison.Ordinal);
    }

    [Fact]
    public async Task The_residence_list_renders_for_an_applicant_on_the_application()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.OwnerEmail);

        var response = await client.GetAsync($"/Residences/ListPartial/{app.ApplicationId}");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task The_add_residence_modal_opens_for_an_applicant_on_a_draft()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.OwnerEmail);

        var response = await client.GetAsync($"/Residences/Form/0?applicationId={app.ApplicationId}");

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);

        // The partial moved folders at the same time as the actions. A miss there renders an empty
        // body with a 200, so the form itself has to be asserted rather than the status code.
        var html = await response.Content.ReadAsStringAsync();

        Assert.Contains("AddressLine1", html, StringComparison.Ordinal);
    }

    [Fact]
    public async Task An_existing_residence_opens_for_editing_and_for_removal()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.OwnerEmail);

        var edit = await client.GetAsync(
            $"/Residences/Form/{app.ResidenceId}?applicationId={app.ApplicationId}");
        var remove = await client.GetAsync(
            $"/Residences/ConfirmDelete/{app.ResidenceId}?applicationId={app.ApplicationId}");

        Assert.Equal(HttpStatusCode.OK, edit.StatusCode);
        Assert.Equal(HttpStatusCode.OK, remove.StatusCode);

        // The stored address comes back in the form rather than an empty one, which is what
        // separates "the route resolved" from "the route resolved and found the right row".
        Assert.Contains("12 Second Street", await edit.Content.ReadAsStringAsync(), StringComparison.Ordinal);
    }

    [Fact]
    public async Task A_residence_on_someone_elses_application_is_not_reachable_by_its_own_id()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.StrangerEmail);

        // The id is real and correct. It is only ever looked up through the application it belongs
        // to, so knowing the number is not enough.
        var response = await client.GetAsync(
            $"/Residences/Form/{app.ResidenceId}?applicationId={app.ApplicationId}");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task Another_applicant_cannot_open_the_residence_list()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.StrangerEmail);

        var response = await client.GetAsync($"/Residences/ListPartial/{app.ApplicationId}");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task Another_applicant_cannot_open_the_residence_modal()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.StrangerEmail);

        var response = await client.GetAsync($"/Residences/Form/0?applicationId={app.ApplicationId}");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task A_property_manager_may_read_the_list_but_is_refused_the_modal()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.ManagerEmail);

        var list = await client.GetAsync($"/Residences/ListPartial/{app.ApplicationId}");
        var form = await client.GetAsync($"/Residences/Form/0?applicationId={app.ApplicationId}");

        // Viewing and editing are different answers: a manager reads the application, and only an
        // applicant on it adds to it. 403 rather than 404, because they can already see it exists.
        Assert.Equal(HttpStatusCode.OK, list.StatusCode);
        Assert.Equal(HttpStatusCode.Redirect, form.StatusCode);
        Assert.Contains("AccessDenied", form.Headers.Location?.OriginalString, StringComparison.Ordinal);
    }

    [Fact]
    public async Task The_old_routes_are_gone()
    {
        var client = await app.SignInAsync(PropertyManagementApplication.OwnerEmail);

        var response = await client.GetAsync(
            $"/RentalApplications/ResidenceListPartial/{app.ApplicationId}");

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }
}
